/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Naloga1;

import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;

/**
 *
 * @author seba
 */
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
        this.setLocationRelativeTo(null);
        izbire1e.setDisplayedMnemonicIndex(8);
        izbire1b.setDisplayedMnemonicIndex(8);
        izbire2e.setDisplayedMnemonicIndex(8);
        jButton2.setDisplayedMnemonicIndex(8);
        jButton3.setDisplayedMnemonicIndex(8);
        jButton6.setDisplayedMnemonicIndex(8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        status = new javax.swing.JLabel();
        orodna = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vnos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kraj = new javax.swing.JComboBox<>();
        dodaj = new javax.swing.JRadioButton();
        odstraniPrvega = new javax.swing.JRadioButton();
        odstraniIzbranega = new javax.swing.JRadioButton();
        izvedi = new javax.swing.JButton();
        izbraniIndeks = new javax.swing.JSpinner();
        dvojniki = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        sporocila = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        datoteka = new javax.swing.JMenu();
        odpri = new javax.swing.JMenuItem();
        pobrisi = new javax.swing.JMenuItem();
        izhod = new javax.swing.JMenuItem();
        izbire1 = new javax.swing.JMenu();
        izbire1s = new javax.swing.JMenuItem();
        izbire1e = new javax.swing.JMenuItem();
        izbire1b = new javax.swing.JMenuItem();
        izbire1a = new javax.swing.JMenuItem();
        izbire2 = new javax.swing.JMenu();
        izbire2m = new javax.swing.JMenuItem();
        izbire2e = new javax.swing.JMenuItem();
        izbire2v = new javax.swing.JMenuItem();
        izbire2l = new javax.swing.JMenuItem();
        izbire2j = new javax.swing.JMenuItem();
        izbire2a = new javax.swing.JMenuItem();
        pomoc = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        status.setText(" Status: ");
        getContentPane().add(status, java.awt.BorderLayout.SOUTH);

        orodna.setRollover(true);

        jButton1.setMnemonic('s');
        jButton1.setText("Izbire1 S");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        orodna.add(jButton1);

        jButton2.setMnemonic('e');
        jButton2.setText("Izbire1 E");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        orodna.add(jButton2);

        jButton3.setMnemonic('b');
        jButton3.setText("Izbire1 B");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        orodna.add(jButton3);

        jButton4.setMnemonic('a');
        jButton4.setText("Izbire1 A");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        orodna.add(jButton4);

        jButton5.setMnemonic('m');
        jButton5.setText("Izbire2 M");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        orodna.add(jButton5);

        jButton6.setMnemonic('e');
        jButton6.setText("Izbire2 E");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        orodna.add(jButton6);

        jButton7.setMnemonic('v');
        jButton7.setText("Izbire2 V");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        orodna.add(jButton7);

        jButton8.setMnemonic('l');
        jButton8.setText("Izbire2 L");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        orodna.add(jButton8);

        jButton9.setMnemonic('j');
        jButton9.setText("Izbire2 J");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        orodna.add(jButton9);

        jButton10.setMnemonic('a');
        jButton10.setText("Izbire2 A");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        orodna.add(jButton10);

        getContentPane().add(orodna, java.awt.BorderLayout.PAGE_START);

        jLabel1.setText("Vnos: ");

        jLabel2.setText("Prebivališče:");

        kraj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Postojna", "Ljubljana", "Logatec", "Koper", "Sežana", "Lokev", "Tolmin", "Divača" }));
        kraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krajActionPerformed(evt);
            }
        });

        buttonGroup1.add(dodaj);
        dodaj.setText("Dodaj");

        buttonGroup1.add(odstraniPrvega);
        odstraniPrvega.setText("Odstrani prvega");

        buttonGroup1.add(odstraniIzbranega);
        odstraniIzbranega.setText("Odstrani izbranega");

        izvedi.setText("Izvedi izbrano akcijo");
        izvedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izvediActionPerformed(evt);
            }
        });

        izbraniIndeks.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        izbraniIndeks.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                prikaziElement(evt);
            }
        });

        dvojniki.setText("Prepovej dvojnike");
        dvojniki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvojnikiActionPerformed(evt);
            }
        });

        jLabel3.setText("Sporočila: ");

        jLabel4.setText("Izberi element:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vnos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kraj, javax.swing.GroupLayout.Alignment.TRAILING, 0, 204, Short.MAX_VALUE)
                            .addComponent(izbraniIndeks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dodaj)
                                .addGap(18, 18, 18)
                                .addComponent(odstraniPrvega)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(odstraniIzbranega))
                            .addComponent(dvojniki))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(izvedi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(sporocila, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(kraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(izbraniIndeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dodaj)
                    .addComponent(odstraniPrvega)
                    .addComponent(odstraniIzbranega))
                .addGap(18, 18, 18)
                .addComponent(dvojniki)
                .addGap(5, 5, 5)
                .addComponent(izvedi)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(sporocila, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        datoteka.setMnemonic('d');
        datoteka.setText("Datoteka");

        odpri.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        odpri.setMnemonic('o');
        odpri.setText("Odpri");
        odpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpriActionPerformed(evt);
            }
        });
        datoteka.add(odpri);

        pobrisi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        pobrisi.setMnemonic('p');
        pobrisi.setText("Pobriši");
        pobrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobrisiActionPerformed(evt);
            }
        });
        datoteka.add(pobrisi);

        izhod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        izhod.setMnemonic('i');
        izhod.setText("Izhod");
        izhod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izhodActionPerformed(evt);
            }
        });
        datoteka.add(izhod);

        jMenuBar1.add(datoteka);

        izbire1.setMnemonic('1');
        izbire1.setText("Izbire1");

        izbire1s.setMnemonic('s');
        izbire1s.setText("Izbire1 S");
        izbire1s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbire1sActionPerformed(evt);
            }
        });
        izbire1.add(izbire1s);

        izbire1e.setMnemonic('e');
        izbire1e.setText("Izbire1 E");
        izbire1e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbire1eActionPerformed(evt);
            }
        });
        izbire1.add(izbire1e);

        izbire1b.setMnemonic('b');
        izbire1b.setText("Izbire1 B");
        izbire1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbire1bActionPerformed(evt);
            }
        });
        izbire1.add(izbire1b);

        izbire1a.setMnemonic('a');
        izbire1a.setText("Izbire1 A");
        izbire1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbire1aActionPerformed(evt);
            }
        });
        izbire1.add(izbire1a);

        jMenuBar1.add(izbire1);

        izbire2.setMnemonic('2');
        izbire2.setText("Izbire2");

        izbire2m.setMnemonic('m');
        izbire2m.setText("Izbire2 M");
        izbire2m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbire2mActionPerformed(evt);
            }
        });
        izbire2.add(izbire2m);

        izbire2e.setMnemonic('e');
        izbire2e.setText("Izbire2 E");
        izbire2e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbire2eActionPerformed(evt);
            }
        });
        izbire2.add(izbire2e);

        izbire2v.setMnemonic('v');
        izbire2v.setText("Izbire2 V");
        izbire2v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbire2vActionPerformed(evt);
            }
        });
        izbire2.add(izbire2v);

        izbire2l.setMnemonic('l');
        izbire2l.setText("Izbire2 L");
        izbire2l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbire2lActionPerformed(evt);
            }
        });
        izbire2.add(izbire2l);

        izbire2j.setMnemonic('j');
        izbire2j.setText("Izbire2 J");
        izbire2j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbire2jActionPerformed(evt);
            }
        });
        izbire2.add(izbire2j);

        izbire2a.setMnemonic('a');
        izbire2a.setText("Izbire2 A");
        izbire2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbire2aActionPerformed(evt);
            }
        });
        izbire2.add(izbire2a);

        jMenuBar1.add(izbire2);

        pomoc.setMnemonic('p');
        pomoc.setText("Pomoč");
        jMenuBar1.add(pomoc);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpriActionPerformed
        JFileChooser jfc = new JFileChooser();
        //zanima ans če je user kaj zbrau
        jfc.showOpenDialog(this);
    }//GEN-LAST:event_odpriActionPerformed

    private void izbire1sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbire1sActionPerformed
        dodajCrko('S');
    }//GEN-LAST:event_izbire1sActionPerformed

    private void izbire1eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbire1eActionPerformed
       dodajCrko('E');
    }//GEN-LAST:event_izbire1eActionPerformed

    private void izbire1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbire1bActionPerformed
        dodajCrko('B');
    }//GEN-LAST:event_izbire1bActionPerformed

    private void izbire1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbire1aActionPerformed
        dodajCrko('A');
    }//GEN-LAST:event_izbire1aActionPerformed

    private void izbire2mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbire2mActionPerformed
        dodajCrko('M');
    }//GEN-LAST:event_izbire2mActionPerformed

    private void izbire2eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbire2eActionPerformed
        dodajCrko('E');
    }//GEN-LAST:event_izbire2eActionPerformed

    private void izbire2vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbire2vActionPerformed
        dodajCrko('V');
    }//GEN-LAST:event_izbire2vActionPerformed

    private void izbire2lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbire2lActionPerformed
        dodajCrko('L');
    }//GEN-LAST:event_izbire2lActionPerformed

    private void izbire2jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbire2jActionPerformed
        dodajCrko('J');
    }//GEN-LAST:event_izbire2jActionPerformed

    private void izbire2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbire2aActionPerformed
        dodajCrko('A');
    }//GEN-LAST:event_izbire2aActionPerformed

    private void krajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_krajActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dodajCrko('S');
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         dodajCrko('E');
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         dodajCrko('B');
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         dodajCrko('A');
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         dodajCrko('M');
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         dodajCrko('E');
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         dodajCrko('V');
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         dodajCrko('L');
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         dodajCrko('J');
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         dodajCrko('A');
    }//GEN-LAST:event_jButton10ActionPerformed

    private void dvojnikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvojnikiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dvojnikiActionPerformed

    private void izvediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izvediActionPerformed
        if (dodaj.isSelected()) {
            String vneseno = vnos.getText();
            if (!vneseno.isEmpty()) {
                if (!dvojniki.isSelected() || ((DefaultComboBoxModel)kraj.getModel()).getIndexOf(vneseno) == -1) {
                    kraj.addItem(vneseno);
                    sporocila.setText("Dodajam");
                }

            }

        }
        else if (kraj.getItemCount() != 0) {
            if (odstraniPrvega.isSelected()) {
                kraj.removeItemAt(0);
                sporocila.setText("Odstranjujem prvega");
            }
            else if (odstraniIzbranega.isSelected()) {
                kraj.removeItemAt(kraj.getSelectedIndex());
                sporocila.setText("Odstranjujem izbranega");
            }
        }
        {

        }
    }//GEN-LAST:event_izvediActionPerformed

    private void pobrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobrisiActionPerformed
        status.setText(" Status: ");
        sporocila.setText("");
    }//GEN-LAST:event_pobrisiActionPerformed

    private void izhodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izhodActionPerformed
        System.exit(0);
    }//GEN-LAST:event_izhodActionPerformed

    private void prikaziElement(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_prikaziElement
        int izbrani = Integer.parseInt(izbraniIndeks.getValue().toString());

        if (kraj.getItemCount() > izbrani) {
            sporocila.setText(kraj.getItemAt(izbrani));
        }
        else{
            sporocila.setText("Ni elementa");
        }
    }//GEN-LAST:event_prikaziElement

    private void dodajCrko(char crka){
        status.setText(status.getText() + crka);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu datoteka;
    private javax.swing.JRadioButton dodaj;
    private javax.swing.JCheckBox dvojniki;
    private javax.swing.JMenu izbire1;
    private javax.swing.JMenuItem izbire1a;
    private javax.swing.JMenuItem izbire1b;
    private javax.swing.JMenuItem izbire1e;
    private javax.swing.JMenuItem izbire1s;
    private javax.swing.JMenu izbire2;
    private javax.swing.JMenuItem izbire2a;
    private javax.swing.JMenuItem izbire2e;
    private javax.swing.JMenuItem izbire2j;
    private javax.swing.JMenuItem izbire2l;
    private javax.swing.JMenuItem izbire2m;
    private javax.swing.JMenuItem izbire2v;
    private javax.swing.JSpinner izbraniIndeks;
    private javax.swing.JMenuItem izhod;
    private javax.swing.JButton izvedi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> kraj;
    private javax.swing.JMenuItem odpri;
    private javax.swing.JRadioButton odstraniIzbranega;
    private javax.swing.JRadioButton odstraniPrvega;
    private javax.swing.JToolBar orodna;
    private javax.swing.JMenuItem pobrisi;
    private javax.swing.JMenu pomoc;
    private javax.swing.JLabel sporocila;
    private javax.swing.JLabel status;
    private javax.swing.JTextField vnos;
    // End of variables declaration//GEN-END:variables
}
